import Head from 'next/head'
import Image from 'next/image'
import styles from "../styles/Home.module.css";
import {
  GoogleProvider,
  FacebookProvider,
  GithubProvider,
} from "./../config/firebaseAuthMethod";
import { useDispatch, useSelector } from "react-redux";
import { signIn } from "./../redux/actions/authActions";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  const dispatch = useDispatch();
  const router = useRouter();
  const { auth } = useSelector((data) => data);
  console.log(auth);

  const handleClick = async (provider) => {
    const { user } = await dispatch(signIn(provider));
    console.log(user);
    if (user !== "") router.push("/home");
  };

  useEffect(() => {
    if (auth.dataAuth !== "") {
      router.push("/home");
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <button
            onClick={() => handleClick(GoogleProvider)}
            className={styles.card}
          >
            Google
          </button>

          <button
            onClick={() => handleClick(FacebookProvider)}
            className={styles.card}
          >
            Facebook
          </button>

          <button
            onClick={() => handleClick(GithubProvider)}
            className={styles.card}
          >
            Github
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
